### PR TITLE
Feature #157795868 implement a sidebar for home page.

### PR DESCRIPTION
**Pull request by asheuh**
#### What does this PR do?
Have a user navigate to the relevant pages

#### Description of Task to be completed?
Navigate to the all requests page
Navigate to the approved request
Navigate to the resolved page
View profile
Create requests

#### How should this be manually tested?
Clone the repo and cd in the clone repo
Navigate to the file name home.html and open with your favorite browser

#### What are the relevant pivotal tracker stories?
#157795868

### CODE REVIEW

**Comment by Slinjez** [comment]
Well explained PR

**Comment by asheuh** [comment]
Thanks for viewing my PR. Ill make the changes pointed out

**Comment by Slinjez** [comment]
nice sidebar

**Comment by asheuh** [comment]
Cool bro, appreciated

**Pull request merged**
